env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  mocha: true

extends:
  - eslint:recommended
  - airbnb-base
  - plugin:node/recommended

plugins:
  - mocha-no-only

parserOptions:
  ecmaVersion: 12

rules:
  no-trailing-spaces: ["error", { "ignoreComments": true }]
  max-len: ["error", { "code": 120 }]
  no-underscore-dangle: "off"
  no-inner-declarations: "off"
  no-console: "off"
  camelcase: "warn"
  no-param-reassign: "warn"
  func-names: "warn"
  no-restricted-syntax: "warn"
  guard-for-in: "warn"
  eqeqeq: "warn"
  indent: 
    - "error"
    - 2
    - MemberExpression: "off"
  node/no-unpublished-require: "off"
  import/order: "off"
  radix: "off"
  no-new: "off"
  no-plusplus: "off" 
  no-multi-str: "off"
  mocha-no-only/mocha-no-only: ["error"]

ignorePatterns:
  - "static/**/*.js"

overrides:
  - files:
      - "tests/*.js"
      - "test/*.js"
    rules:
      no-unused-expressions: "off"
      no-shadow: "off"
  - files:
      - "migrations/*.js"
    rules:
      max-len: "off"
