env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  mocha: true

parser: "@typescript-eslint/parser"

extends:
  - eslint:recommended
  - airbnb-base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript

plugins:
  - "@typescript-eslint"
  - mocha-no-only

parserOptions:
  ecmaVersion: 12

rules:
  no-trailing-spaces: ["error", { "ignoreComments": true }]
  max-len: ["error", { "code": 120 }]
  no-underscore-dangle: "off"
  no-inner-declarations: "off"
  no-console: "off"
  camelcase: "warn"
  func-names: "warn"
  no-restricted-syntax: "warn"
  guard-for-in: "warn"
  eqeqeq: "warn"
  indent: 
    - "error"
    - 2
    - MemberExpression: "off"
  node/no-unpublished-require: "off"
  import/order: "off"
  radix: "off"
  no-new: "off"
  no-plusplus: "off" 
  no-multi-str: "off"
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": ["error", { "ignoreRestSiblings": true }]
  "@typescript-eslint/explicit-module-boundary-types": "error"
  "@typescript-eslint/no-empty-function": "off"
  "@typescript-eslint/no-var-requires": "off"
  mocha-no-only/mocha-no-only: ["error"]
  import/extensions: ["error", {
    js: "never",
    ts: "never",
  }]

overrides:
  - files:
      - "tests/*.js"
      - "test/*.js"
      - "*.spec.js"
    rules:
      no-unused-expressions: "off"
      no-shadow: "off"
  - files:
      - "migrations/*.js"
    rules:
      max-len: "off"
      func-names: "off"
