export type Psychologist = {
    dossierNumber: string,
    firstNames: string,
    lastName: string,
    archived: boolean,
    state: string,
    adeli: string,
    address: string,
    diploma: string,
    phone: string,
    email: string,
    personalEmail: string,
    website: string,
    teleconsultation: boolean,
    description: string,
    training: string,
    departement: string,
    university: string,
    declaredUniversityId?: string,
    assignedUniversityId: string,
    region: string,
    languages: string,
    active: boolean,
    inactiveUntil: string,
}
