module.exports = {
  '01': 'cas particulier',
  '02': 'Picardie Jules Verne',
  '03': 'Clermont-Auvergne (UCA)',
  '04': 'Aix-Marseille',
  '05': 'Aix-Marseille',
  '06': "Côte d'Azur",
  '07': 'Grenoble Alpes',
  '08': 'Reims Champagne-Ardenne',
  '09': 'Toulouse Midi-Pyrénées',
  10: 'Reims Champagne-Ardenne',
  11: 'Occitanie Ouest',
  12: 'Toulouse Midi-Pyrénées',
  13: 'Aix-Marseille',
  14: 'Caen Normandie',
  15: 'Clermont-Auvergne (UCA)',
  16: 'Poitiers',
  17: 'La Rochelle',
  18: 'Orléans',
  19: 'Limoges',
  '2A': 'Corsica Pasquale Paoli',
  '2B': 'Corsica Pasquale Paoli',
  21: 'Dijon',
  22: 'Rennes',
  23: 'Limoges',
  24: 'Bordeaux',
  25: 'Franche-Comté',
  26: 'Grenoble Alpes',
  27: 'cas particulier',
  28: 'Orléans',
  29: 'Bretagne Occidentale',
  30: 'Occitanie Ouest',
  31: 'Toulouse Midi-Pyrénées',
  32: 'Toulouse Midi-Pyrénées',
  33: 'Bordeaux',
  34: 'Occitanie Ouest',
  35: 'Rennes',
  36: 'on ne sait pas encore...',
  37: 'Tours',
  38: 'Grenoble Alpes',
  39: 'Franche-Comté',
  40: 'Bordeaux',
  41: 'Tours',
  42: 'Saint-Etienne - Jean Monnet',
  43: 'Clermont-Auvergne (UCA)',
  44: 'Nantes',
  45: 'Orléans',
  46: 'Toulouse Midi-Pyrénées',
  47: 'Bordeaux',
  48: 'Occitanie Ouest',
  49: 'Angers',
  50: 'Caen Normandie',
  51: 'Reims Champagne-Ardenne',
  52: 'Reims Champagne-Ardenne',
  53: 'Le Mans Université',
  54: 'Lorraine Sud-Nancy',
  55: 'Lorraine Sud-Nancy',
  56: 'Bretagne Sud',
  57: 'Lorraine Sud-Nancy',
  58: 'Dijon',
  59: 'cas particulier',
  60: 'Picardie Jules Verne',
  61: 'Caen Normandie',
  62: 'Lille',
  63: 'Clermont-Auvergne (UCA)',
  64: "Pau et Pays de l'Adour (UPPA)",
  65: 'Toulouse Midi-Pyrénées',
  66: 'Occitanie Ouest',
  67: 'Strasbourg (UNISTRA)',
  68: 'Haute-Alsace (UHA)',
  69: 'cas particulier',
  70: 'Franche-Comté',
  71: 'Dijon',
  72: 'Le Mans Université',
  73: 'Savoie Mont-Blanc',
  74: 'Savoie Mont-Blanc',
  75: 'Paris Descartes (Université de Paris)',
  76: 'cas particulier',
  77: 'Paris Est Créteil (UPEC)',
  78: 'Versailles Saint-Quentin (UVSQ)',
  79: 'Poitiers',
  80: 'Picardie Jules Verne',
  81: 'Toulouse Midi-Pyrénées',
  82: 'Toulouse Midi-Pyrénées',
  83: 'Toulon',
  84: 'Avignon',
  85: 'Nantes',
  86: 'Poitiers',
  87: 'Limoges',
  88: 'Lorraine Sud-Nancy',
  89: 'Dijon',
  90: 'Franche-Comté',
  91: 'Evry',
  92: 'Paris Saclay',
  93: 'Sorbonne Paris Nord',
  94: 'Paris Est Créteil (UPEC)',
  95: 'Cergy Paris Université',
  971: 'Antilles - Pôle Guadeloupe',
  972: 'Antilles - Pôle Martinique',
  973: '',
  974: 'La Réunion',
  976: '',
};
