import fs from 'fs';
// This file needs to be generated by createInstitutionNames.ts
import institutionsName from './institutionsName.json';
import stringSimilarity from 'string-similarity';
// This file can be exported via Metabase
import patientsInstitution from './patientsInstitution.json';

const universities = {};

patientsInstitution.map((institution) => institution.institutionName)
        .filter((institution) => institution)
        .map((institution) => {
          const matches = stringSimilarity.findBestMatch(institution, institutionsName);
          return { old: institution, ...matches.bestMatch };
        })
        .sort((a, b) => a.rating - b.rating)
        .forEach((institution) => {
          universities[institution.old] = {
            target: institution.target,
            rating: institution.rating,
            go: institution.rating > 0.7,
          };
        });

fs.writeFileSync('newPatientsInstitution.json',
  JSON.stringify(
    universities,
    null, 2,
  ));
