/* eslint-disable max-len */
const eligibleSchools = [
  'Aix-Marseille Université (AMU)',
  'Arts et Métiers Sciences et Technologies (Arts et Métiers)',
  'Audencia Business School (Audencia)',
  'Avignon Université (AU)',
  'Bordeaux INP (IPB)',
  'Brest Business School (Brest BS)',
  "BUILDERS École d'ingénieurs (BUILDERS Caen)",
  'Burgundy School of Business (BSB)',
  'Casa de Velázquez de Madrid (CVZ)',
  'Centrale Lille Institut (CLI)',
  'Centrale Lyon (EC Lyon)',
  'Centrale Méditerranée',
  'CESI (CESI)',
  'Collège de France (Grand établissement)',
  'Conservatoire national des arts et métiers (CNAM)',
  'CY Cergy Paris Université (CYU)',
  'DCG (comptable et gestion)',
  'ECAM Rennes Louis de Broglie (ECAM Rennes)',
  'ECAM-EPMI (ECAM-EPMI)',
  'École catholique des arts et métiers (ECAM Lasalle)',
  "École centrale d'électronique (ECE)",
  "École d'ingénieur d'agro-développement international (ISTOM)",
  "École d'ingénieurs de Purpan (EI Purpan)",
  "École d'ingénieurs des sciences aérospatiales (ELISA)",
  'École de biologie industrielle (EBI)',
  "École de l'air et de l'espace (Grand établissement)",
  'École de management de Normandie (EM Normandie)',
  'École des hautes études commerciales de Paris (HEC Paris)',
  'École des hautes études commerciales du nord (Edhec)',
  'École des hautes études en sciences sociales (EHESS)',
  "École française d'Athènes (EFA)",
  "École française d'Extrême-Orient (EFEO)",
  'École française de Rome (EFR)',
  "École nationale d'ingénieurs de Brest (ENIB)",
  "École nationale de l'aviation civile (ENAC)",
  'École nationale de la météorologie (ENM)',
  'École nationale des ponts et chaussées (ENPC)',
  'École nationale des sciences géographiques (ENSG-Géomatique)',
  "École nationale des travaux publics de l'État (ENTPE)",
  "École nationale du génie de l'eau et de l'environnement de Strasbourg (ENGEES)",
  "École nationale supérieure d'architecture de Clermont-Ferrand (ENSACF)",
  "École nationale supérieure d'architecture de Normandie (Ensa de Normandie)",
  "École nationale supérieure d'architecture de Paris-Belleville (ENSAPB)",
  "École nationale supérieure d'architecture de Paris-La Villette (ENSAPLV)",
  "École nationale supérieure d'architecture de Paris-Malaquais (ENSAPM)",
  "École nationale supérieure d'architecture de Strasbourg (ENSAS)",
  "École nationale supérieure d'architecture de Toulouse (ENSA Toulouse)",
  'École nationale supérieure d’architecture de Versailles (ENSA-V)',
  "École nationale supérieure d'architecture et de paysage de Lille (ENSAPL)",
  "École nationale supérieure d'informatique pour l'industrie et l'entreprise (ENSIIE)",
  "École nationale supérieure d'ingénieurs de Caen (ENSI Caen)",
  'École nationale supérieure de création industrielle - Les Ateliers (Ensci-Les Ateliers)',
  'École nationale supérieure de formation de l’enseignement agricole (ENSFEA)',
  "École nationale supérieure de l'électronique et de ses applications de Cergy (ENSEA)",
  "École nationale supérieure de mécanique et d'aérotechnique de Poitiers (ISAE-ENSMA)",
  'École nationale supérieure de mécanique et des microtechniques (ENSMM Besançon)',
  'École nationale supérieure de paysage (ENSP)',
  'École nationale supérieure de techniques avancées Bretagne (ENSTA Bretagne)',
  'École nationale supérieure des arts décoratifs (ÉnsAD-Paris)',
  'École nationale supérieure des arts et industries textiles (ENSAIT)',
  'École nationale supérieure des arts et techniques du théâtre (ENSATT)',
  'École nationale supérieure des sciences agronomiques de Bordeaux Aquitaine (Bordeaux Sciences Agro)',
  "École nationale supérieure des sciences de l'information et des bibliothèques (ENSSIB)",
  'École nationale supérieure du pétrole et des moteurs (IFP school)',
  'École nationale supérieure Louis Lumière (ENS Louis Lumière)',
  'École nationale supérieure maritime (ENSM)',
  "École nationale vétérinaire d'Alfort (ENVA)",
  'École nationale vétérinaire de Toulouse (ENVT)',
  "École nationale vétérinaire, agroalimentaire et de l'alimentation, Nantes-Atlantique (ONIRIS)",
  'École navale (EN)',
  'École normale supérieure de Lyon (ENS de Lyon)',
  "École pour l'informatique et les techniques avancées (EPITA)",
  "École spéciale d'architecture (ÉSA)",
  "École spéciale de mécanique et d'électricité (ESME Sudria)",
  "École spéciale des travaux publics, du bâtiment et de l'industrie (ESTP)",
  'École spéciale militaire de Saint-Cyr (ESM ST CYR)',
  'École supérieure angevine en informatique et productique (ESAIP)',
  'École supérieure d’agriculture (ESA)',
  "École supérieure d'arts et médias de Caen - Cherbourg (ÉSAM Caen/Cherbourg)",
  "École supérieure d'électronique de l'Ouest (ESEO)",
  "École supérieure d'informatique électronique automatique (ESIEA)",
  "École supérieure d'ingénieurs des travaux de la construction de Metz (ESITC de Metz)",
  "École supérieure d'ingénieurs des travaux de la construction de Paris (ESITC Paris)",
  "École supérieure d'ingénieurs en génie électrique (ESIGELEC)",
  "Ecole supérieure de journalisme de Lille (ESJ Lille)",
  "École supérieure de l'aéronautique et de l'espace (ISAE-SUPAERO)",
  "École supérieure de l'électronique et du numérique de Brest (Yncréa Ouest)",
  'École supérieure du bâtiment et des travaux publics (ISBA TP)',
  'École supérieure du commerce de Paris (ISC Paris Business School)',
  "École supérieure des sciences commerciales d'Angers (ESSCA)",
  'École supérieure des sciences économiques et commerciales (Essec)',
  'École supérieure des techniques aéronautiques et de construction automobile (ESTACA)',
  'École supérieure des technologies et des affaires de Belfort (ESTA Belfort)',
  'École supérieure des technologies industrielles avancées (ESTIA)',
  'École supérieure du bois (ESB Nantes)',
  'EIGSI La Rochelle (EIGSI)',
  "ENOES - École de l'Expertise Comptable et de l'Audit à Paris",
  "EPF - École d'ingénieurs (EPF)",
  "EPITECH - École pour l'informatique et les nouvelles technologies",
  'ESCP Business School (ESCP)',
  'ESIEE Paris',
  'ESIEE-IT',
  'Excelia Group (Excelia)',
  "Facultés libres de l'Ouest (FLO)",
  'Facultés Libres de Philosophie et de Psychologie (IPC)',
  "Groupe Institut catholique d'arts et métiers (Groupe ICAM)",
  "Grenoble Ecole de Management (GEM)",
  "Hautes études d'ingénieur (HEI)",
  'IAE Paris - Sorbonne Business School (IAE de Paris)',
  'ICN Business School (ICN)',
  'IFSI',
  'Institut catholique de Lille (ICL)',
  'Institut catholique de Lyon (UCLY)',
  'Institut catholique de Paris (ICP)',
  'Institut catholique de Rennes (ICR)',
  'Institut catholique de Toulouse (ICT)',
  'Institut catholique de Vendée (ICES)',
  "Institut d'économie scientifique et de gestion (IÉSEG)",
  "Institut d'ingénierie informatique de Limoges (3IL)",
  'Institut des relations publiques et de la communication d’Angers (Ircom)',
  "Institut européen d'administration des affaires (INSEAD)",
  "Institut français d'archéologie orientale du Caire (IFAO)",
  'Institut français de la mode (IFM Paris)',
  'Institut Mines-Télécom, au périmètre des écoles IMT Atlantique, Lille Douai, Albi, Alès, Mines Saint-Étienne et Institut Mines-Télécom Business school (IMT)',
  "Institut national d'enseignement supérieur pour l'agriculture, l'alimentation et l'environnement (Institut Agro)",
  "Institut national d'histoire de l'art (INHA)",
  'Institut national des langues et civilisations orientales (INALCO)',
  'Institut national des sciences appliquées Centre Val de Loire (INSA Centre Val de Loire)',
  'Institut national des sciences appliquées de Lyon (INSA de Lyon)',
  'Institut national des sciences appliquées de Rouen Normandie (INSA de Rouen Normandie)',
  'Institut national des sciences appliquées de Strasbourg (INSA de Strasbourg)',
  'Institut national des sciences appliquées de Toulouse (INSA de Toulouse)',
  'Institut national des sciences et techniques nucléaires (INSTN)',
  'Institut national du patrimoine (Inp)',
  'Institut national du service public (INSP)',
  "Institut national du sport, de l'expertise et de la performance (INSEP)",
  "Institut national supérieur de formation et de recherche pour l'éducation inclusive (INSEI)",
  'Institut national universitaire Jean-François Champollion (INU Albi)',
  'Institut polytechnique de Paris (IP Paris)',
  'Institut polytechnique des sciences avancées (IPSA)',
  'Institut polytechnique UniLaSalle (UniLaSalle)',
  'Institut protestant de théologie (IPT)',
  "Institut Sup'Biotech de Paris (Sup'Biotech)",
  "Institut supérieur d'agriculture de Lille (ISA Lille)",
  'Institut supérieur d’agriculture Rhône-Alpes (Isara-Lyon)',
  "Institut supérieur d'électronique de Paris (ISEP)",
  "Institut supérieur de l'aéronautique et de l'espace (ISAE-SUPAERO)",
  "Institut supérieur de l'électronique et du numérique de Brest (Yncréa Ouest)",
  'Institut supérieur du bâtiment et des travaux publics (ISBA TP)',
  'Institut supérieur du commerce de Paris (ISC Paris Business School)',
  'Institut textile et chimique (ITECH)',
  'IPAG Business School',
  'IRTS',
  'ISAE-Supméca',
  'ISEN Yncréa Méditerranée (ISEN Yncréa Méditerranée)',
  'ISMANS',
  'Junia',
  'KEDGE Business School (KEDGE BS)',
  'La Rochelle Université (Université La Rochelle)',
  'Le Mans Université (LMU)',
  'Montpellier Business School (MBS)',
  "Muséum national d'histoire naturelle (MNHN)",
  'Nantes Université (NU)',
  'Neoma Business School (Neoma BS)',
  'Paris School of Business (PSB)',
  'Rennes School of Business (Rennes SB)',
  'Sciences Po (IEP de Paris)',
  "Sciences Po Aix (IEP d'Aix-en-Provence)",
  'Sciences Po Bordeaux (IEP de Bordeaux)',
  'Sciences Po Lille (IEP de Lille)',
  'Sciences Po Lyon (IEP de Lyon)',
  'Sciences Po Toulouse (IEP de Toulouse)',
  'Skema Business School (Skema)',
  'Sorbonne Université (Sorbonne U)',
  'Sup de V',
  'Toulouse Business School (TBS)',
  'Toulouse INP (Toulouse INP)',
  'Université Bordeaux Montaigne (UBM)',
  'Université Bretagne Sud (UBS)',
  'Université Claude Bernard - Lyon 1 (Lyon I)',
  'Université Clermont Auvergne (UCA)',
  "Université Côte d'Azur (UCA)",
  "Université d'Angers (UA)",
  "Université d'Artois",
  "Université d'Évry-Val-d'Essonne (UEVE)",
  "Université d'Orléans",
  'Université de Bordeaux (UBx)',
  'Université de Bourgogne (uB)',
  'Université de Bretagne Occidentale (UBO)',
  'Université de Caen Normandie (UNICAEN)',
  'Université de Corse Pasquale Paoli',
  'Université de Franche-Comté (UFC)',
  'Université de Guyane',
  'Université de Haute-Alsace (UHA)',
  'Université de la Nouvelle-Calédonie (UNC)',
  'Université de la Polynésie Française (UPF)',
  'Université de La Réunion (UR)',
  'Université de Lille',
  'Université de Limoges (UNILIM)',
  'Université de Lorraine (UL)',
  'Université de Mayotte',
  'Université de Montpellier (UM)',
  'Université de Nîmes (UNÎMES)',
  "Université de Pau et des Pays de l'Adour (UPPA)",
  'Université de Perpignan Via Domitia (UPVD)',
  'Université de Picardie Jules-Verne (UPJV)',
  'Université de Poitiers',
  'Université de Reims Champagne-Ardenne (URCA)',
  'Université de Rennes (UNIVRENNES)',
  'Université de Rouen Normandie (UNIROUEN)',
  'Université de Strasbourg (UNISTRA)',
  'Université de technologie de Belfort-Montbéliard (UTBM)',
  'Université de Technologie de Compiègne (UTC)',
  'Université de technologie de Troyes (UTT)',
  'Université de technologie Tarbes Occitanie Pyrénées (UTTOP)',
  'Université de Toulon',
  'Université de Tours',
  'Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)',
  'Université des Antilles',
  'Université du Littoral Côte d’Opale (ULCO)',
  'Université Grenoble Alpes (UGA)',
  'Université Gustave Eiffel (UGE)',
  'Université Jean Monnet (UJM)',
  'Université Jean Moulin - Lyon 3 (Lyon III)',
  'Université Le Havre Normandie (UNILEHAVRE)',
  'Université Lumière - Lyon 2 (Lyon II)',
  'Université Paris 1 - Panthéon Sorbonne (Paris 1)',
  'Université Paris 8 - Vincennes - Saint-Denis (Paris VIII)',
  'Université Paris Cité (UP Cité)',
  'Université Paris Nanterre (Paris Nanterre)',
  'Université Paris sciences et lettres (Université PSL)',
  'Université Paris-Est Créteil (UPEC)',
  'Université Paris-Panthéon-Assas (Panthéon-Assas)',
  'Université Paris-Saclay',
  'Université Paul-Valéry - Montpellier 3 (UPV)',
  'Université Polytechnique Hauts-de-France (UPHF)',
  'Université Rennes 2 (Rennes II)',
  'Université Savoie Mont Blanc (USMB)',
  'Université Sorbonne Nouvelle - Paris 3 (Paris III)',
  'Université Sorbonne Paris Nord (USPN)',
  'Université Toulouse - Jean Jaurès (UT2)',
  'Université Toulouse Capitole (UT Capitole)',
  'Université Toulouse III - Paul Sabatier (UT3)',
  'Vet Agro Sup (Vet Agro Sup)',
  'Y SCHOOLS',
];

export default eligibleSchools;
