const universities = [
  "Agence bibliographique de l'enseignement supérieur",
  "Institut national des sciences et industries du vivant et de l'environnement (AgroParisTech)",
  "Université d'Aix-Marseille",
  "Université de Picardie Jules Verne",
  "Université d'Angers",
  "Université des Antilles",
  "Université d'Artois",
  "Académie des sciences d'outre-mer Paris",
  "Avignon Université",
  "Université Marie et Louis Pasteur",
  "Bibliothèque nationale et universitaire de Strasbourg",
  "Université de Bordeaux",
  "Université Bordeaux III",
  "École nationale supérieure des sciences agronomiques de Bordeaux",
  "Université de Brest",
  "Université Bretagne Sud",
  "Université de Caen Normandie",
  "Campus Condorcet",
  "Campus France",
  "Centrale Lille Institut",
  "CentraleSupélec",
  "Chancellerie de Paris",
  "Centre informatique national de l'enseignement supérieur",
  "Université Clermont Auvergne",
  "Conservatoire national des arts et métiers",
  "Centre national d'enseignement à distance",
  "Centre national des œuvres universitaires et scolaires",
  "CNRS Délégation Rhône Auvergne",
  "CNRS Délégation Paris-Normandie",
  "CNRS Délégation Île-de-France Villejuif",
  "CNRS Délégation Île-de-France Meudon",
  "Centre national de la recherche scientifique",
  "Conservatoire national supérieur d'art dramatique",
  "Conservatoire national supérieur de musique et de danse de Paris",
  "Collège de France",
  "ComUE Angers-Le Mans",
  "ComUE Hautes Écoles Sorbonne Arts et Métiers Université",
  "ComUE Université de Lyon",
  "ComUE Normandie Université",
  "ComUE Université Paris Lumières",
  "ComUE Université Paris-Est",
  "ComUE de Toulouse",
  "Université de Corse Pasquale Paoli",
  "Université Côte d'Azur",
  "Centre technique du livre de l'enseignement supérieur",
  "CY Cergy Paris Université",
  "Université Bourgogne Europe",
  "École centrale de Lyon",
  "École centrale de Marseille",
  "École centrale de Nantes",
  "Casa de Velázquez",
  "École française d'Athènes",
  "École française de Rome",
  "École française d'Extrême-orient",
  "École polytechnique",
  "École des hautes études en santé publique",
  "École des hautes études en sciences sociales",
  "École nationale des chartes",
  "École nationale des Ponts et Chaussées - ENPC",
  "École normale supérieure",
  "École nationale supérieure Louis-Lumière",
  "École normale supérieure de Lyon",
  "École normale supérieure Paris-Saclay",
  "École normale supérieure de Rennes",
  "École nationale supérieure d'architecture de Lyon",
  "École nationale supérieure d'architecture de Paris-Belleville",
  "École nationale supérieure d'architecture de Paris Val de Seine",
  "École nationale supérieure d'architecture de Toulouse",
  "Ecole nationale supérieure des arts décoratifs - ENSAD",
  "École nationale de la statistique et de l'analyse de l'information",
  "École nationale supérieure des arts et industries textiles",
  "École nationale supérieure des arts et métiers - ENSAM",
  "École nationale supérieure des arts et techniques du théâtre",
  "École nationale supérieure de chimie de Montpellier",
  "École nationale supérieure de chimie de Paris",
  "École nationale supérieure de chimie de Rennes",
  "École nationale supérieure de l’électronique et de ses applications",
  "École nationale supérieure d'ingénieurs de Caen",
  "École nationale supérieure d'informatique pour l'industrie et l'entreprise",
  "École nationale supérieure de mécanique et d'aérotechnique",
  "École nationale supérieure des métiers de l'image et du son",
  "École nationale supérieure de mécanique et des microtechniques",
  "École nationale supérieure des sciences de l'information et des bibliothèques",
  "École nationale supérieure de techniques avancées - ENSTA",
  "Établissement public d'aménagement universitaire de la région Île-de-France - EPAURIF",
  "École pratique des hautes études",
  "Établissement public du musée du quai Branly - EPMQB",
  "Université d'Evry Val d'Essonne",
  "Fondation Maison des Sciences de l'homme",
  "Fondation nationale des sciences politiques",
  "France université numérique",
  "GIP Agence de mutualisation des universités et établissements d'enseignement supérieur et de recherche - AMUE",
  "GIP Numérique de Bretagne",
  "GIP Bibliothèque universitaire des langues et civilisations",
  "GIP Campus UGA Valence Drôme Ardèche",
  "GIP Agence Erasmus + Éducation-Formation",
  "GIP Réseau national de télécommunications pour la technologie, l'enseignement et la recherche - RENATER",
  "Université Grenoble Alpes",
  "Université Gustave Eiffel",
  "Université de Guyane",
  "Institut d'administration des entreprises de Paris",
  "Institut d'études politiques d'Aix-en-Provence",
  "Institut d'études politiques de Bordeaux",
  "Institut d'études politiques de Grenoble",
  "Institut d'études politiques de Lille",
  "Institut d'études politiques de Lyon",
  "Institut d'études politiques de Rennes",
  "Institut d'études politiques de Toulouse",
  "Institut français d'archéologie orientale",
  "Institut Mines-Télécom",
  "École nationale supérieure Mines-Télécom Atlantique Bretagne Pays de la Loire",
  "École nationale supérieure des mines d'Albi-Carmaux",
  "École nationale supérieure des mines d'Alès",
  "Institut national des langues et civilisations orientales",
  "Institut national d'études démographiques - INED",
  "Institut national d'enseignement supérieur pour l'agriculture, l'alimentation et l'environnement - Institut Agro",
  "Institut national d'histoire de l'art",
  "Institut polytechnique de Bordeaux",
  "Institut national polytechnique de Bretagne",
  "Institut national polytechnique Clermont Auvergne",
  "Institut polytechnique de Grenoble",
  "Institut national polytechnique de Toulouse",
  "Institut national de recherche pour l'agriculture, l'alimentation et l'environnement - INRAE",
  "Institut national de recherche en informatique et en automatique - INRIA",
  "Institut national des sciences appliquées Centre Val de Loire",
  "Institut national des sciences appliquées Hauts-de-France",
  "Institut national des sciences appliquées de Lyon",
  "Institut national des sciences appliquées de Rennes",
  "Institut national des sciences appliquées de Rouen",
  "Institut national des sciences appliquées de Strasbourg",
  "Institut national des sciences appliquées de Toulouse",
  "Institut national supérieur de formation et de recherche pour l'éducation inclusive",
  "Institut Agro Dijon",
  "Institut Agro Rennes-Angers ",
  "Institut national universitaire Jean-François Champollion",
  "Institut d'optique Graduate School",
  "Institut de physique du globe de Paris",
  "Institut polytechnique de Paris",
  "Institut de recherche pour le développement",
  "Institut supérieur de l'aéronautique et de l'espace - ISAE",
  "Université de La Réunion",
  "Université de La Rochelle",
  "Université Le Havre Normandie",
  "Le Mans Université",
  "Université de Lille",
  "Université de Limoges",
  "Université du Littoral Côte d'Opale",
  "Université de Lorraine",
  "Université Claude Bernard - Lyon 1",
  "Université Lumière - Lyon 2",
  "Université Jean Moulin - Lyon 3",
  "Université de Mayotte",
  "École nationale supérieure des mines de Paris",
  "Muséum national d'histoire naturelle",
  "Université de Montpellier",
  "Université Paul Valéry",
  "Université de Haute-Alsace",
  "Nantes Université",
  "Nîmes Université",
  "Université de Nouvelle-Calédonie",
  "Observatoire de la Côte d'Azur",
  "Observatoire de Paris",
  "École nationale vétérinaire, agroalimentaire et de l'alimentation de Nantes-Atlantique - ONIRIS",
  "Office national d’information sur les enseignements et les professions - ONISEP",
  "Université d'Orléans",
  "Établissement public du palais de la Porte Dorée",
  "Université Paris II - Paris-Panthéon-Assas",
  "Université Paris Cité",
  "Université Paris I - Panthéon-Sorbonne",
  "Université Paris III - Sorbonne-Nouvelle",
  "Université Paris VIII - Vincennes-Saint-Denis",
  "Université Paris X - Nanterre",
  "Université Paris XII - Paris-Est-Créteil-Val-de-Marne",
  "Université Sorbonne Paris-Nord Villetaneuse",
  "Université Paris-Dauphine-PSL",
  "Université Paris-Saclay",
  "Université de Pau et des Pays de l'Adour",
  "Université de Perpignan Via Domitia",
  "Université de Poitiers",
  "Université de la Polynésie française",
  "Université Paris Sciences et Lettres - PSL",
  "Université de Reims",
  "Université de Rennes",
  "Université Rennes 2",
  "Université de Rouen-Normandie",
  "Université Jean-Monnet",
  "Université de Chambéry -  Savoie Mont-Blanc",
  "Sorbonne Université",
  "Université de Strasbourg",
  "Isae-Supméca",
  "Université de Toulon",
  "Université Toulouse Capitole",
  "Université Toulouse II - Jean Jaurès",
  "Université de Toulouse",
  "Université de Tours",
  "Toulouse School of Economics",
  "Universcience",
  "Université polytechnique Hauts-de-France",
  "Université de technologie de Belfort-Montbéliard",
  "Université de technologie de Compiègne",
  "Université de technologie Tarbes Occitanie Pyrénées ",
  "Université de technologie de Troyes",
  "Université de Versailles-Saint-Quentin-en-Yvelines",
  "Institut national d'enseignement supérieur et de recherche en alimentation, santé animale, sciences agronomiques et de l'environnement - Vetagro Sup",
];

export default universities;
