const universities = [
  'Aix-Marseille',
  'Amiens - Picardie Jules Verne',
  'Angers',
  'Antilles',
  'Artois',
  'Avignon',
  'Bordeaux',
  'Bordeaux III',
  'Bourgogne Europe',
  'Bretagne Occidentale (Brest)',
  'Bretagne Sud',
  'Caen Normandie',
  'Centrale Lille Institut',
  'CentraleSupélec',
  'Clermont Auvergne',
  "Côte d'Azur",
  'Corse Pasquale Paoli',
  'Évry Val d\'Essonne',
  'Franche-Comté',
  'Grenoble Alpes',
  'Guyane',
  'Gustave Eiffel',
  'Haute-Alsace (UHA)',
  'La Réunion',
  'La Rochelle',
  'Le Havre Normandie',
  'Le Mans',
  'Lille',
  'Limoges',
  'Littoral Côte d\'Opale',
  'Lorraine',
  'Lyon 1 - Claude Bernard',
  'Lyon 2 - Lumière',
  'Lyon 3 - Jean Moulin',
  'Mayotte',
  'Montpellier',
  'Nantes',
  'Nîmes',
  'Normandie (Rouen)',
  'Nouvelle-Calédonie',
  'Orléans',
  'Paris Cité',
  'Paris I - Panthéon-Sorbonne',
  'Paris II - Panthéon-Assas',
  'Paris III - Sorbonne Nouvelle',
  'Paris IV - Paris-Sorbonne',
  'Paris VIII - Vincennes-Saint-Denis',
  'Paris X - Nanterre',
  'Paris XII - Paris-Est-Créteil-Val-de-Marne',
  'Paris XIII - Sorbonne Paris Nord',
  'Paris Dauphine-PSL',
  'Paris Saclay',
  "Pau et Pays de l'Adour (UPPA)",
  'Perpignan Via Domitia (UPVD)',
  'Poitiers',
  'Polynésie française',
  'Reims Champagne-Ardenne',
  'Rennes',
  'Rennes 2',
  'Rouen Normandie',
  'Savoie Mont-Blanc (Chambéry)',
  'Strasbourg (UNISTRA)',
  'Toulouse III - Paul Sabatier',
  'Toulon',
  'Tours',
  'Valenciennes et du Hainaut-Cambrésis',
  'Versailles Saint-Quentin (UVSQ)',
];

export default universities;
